sudo: required
language : 
  - go  

services:
  - docker

  
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
  - go get -u github.com/constabulary/gb/...
  
script:
#  - git clone https://github.com/TIBCOSoftware/mashling-lib.git
  - touch mashling-lib.tgz
  - tar cvfz mashling-lib.tgz --exclude=mashling-lib.tgz .
  - find . -not -name "mashling-lib.tgz" -not  -name "\." -not -name "\.\."  -print0 | xargs -0 rm -rf --
  - "git ls-remote --exit-code https://github.com/TIBCOSoftware/mashling-cicd.git ${TRAVIS_BRANCH} ;
    if [ $? -eq 0 ]; then 
        echo \"Branch ${TRAVIS_BRANCH} found on mashling-cicd\" ;
        git clone https://github.com/TIBCOSoftware/mashling-cicd.git --branch ${TRAVIS_BRANCH} --single-branch mashling-cicd ;
    else 
        echo \"Branch ${TRAVIS_BRANCH} not found on mashling-cicd using master\" ;
        git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd ;
    fi"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then    
    pushd mashling-cicd/docker/mashling-lib;
    chmod ugo+x ./build-mashling-lib.sh ;
    ./build-mashling-lib.sh ;
    popd ;
    fi

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

after_success:
  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" tibdocker.tibco.com"
  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
    source ${TRAVIS_BUILD_DIR}/mashling-cicd/scripts/init.sh ;
    mashling::module::postbuild mashling-lib mashling-lib ;
    fi"
notifications:
  email:
    - jpark@tibco.com
    - rpolishe@tibco.com
    - lmekala@tibco.com
    - nthota@tibco.com
    - ykalidin@tibco.com    
