sudo: required
services:
  - docker
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" "
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/TIBCOSoftware/flogo-cli/...
  - go get -u github.com/TIBCOSoftware/flogo-lib/...
  
  
script: 
  - go install ./...
  # - touch test-cli.tgz
  # - tar cvfz test-cli.tgz --exclude=test-cli.tgz .
  # - find . -not -name "test-cli.tgz" -not  -name "\." -not -name "\.\."  -print0 | xargs -0 rm -rf --
  

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export REPO=lmekala/test-cli
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
