sudo: required
language : 
  - go  

services:
  - docker
os:
  - linux
  - osx
  - windows
  
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
  - go get -u github.com/constabulary/gb/...
  
script:
  - touch mashling-lib.tgz
  - tar cvfz mashling-lib.tgz --exclude=mashling-lib.tgz .
  - find . -not -name "mashling-lib.tgz" -not  -name "\." -not -name "\.\."  -print0 | xargs -0 rm -rf --
  - "git ls-remote --exit-code https://github.com/TIBCOSoftware/mashling-cicd.git ${TRAVIS_BRANCH} ;
    if [ $? -eq 0 ]; then 
        echo \"Branch ${TRAVIS_BRANCH} found on mashling-cicd\" ;
        git clone https://github.com/TIBCOSoftware/mashling-cicd.git --branch ${TRAVIS_BRANCH} --single-branch mashling-cicd ;
    else 
        echo \"Branch ${TRAVIS_BRANCH} not found on mashling-cicd using master\" ;
        git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd ;
    fi"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then    
    pushd mashling-cicd/docker/mashling-lib;
    chmod ugo+x ./build-mashling-lib.sh ;
    ./build-mashling-lib.sh ;
    popd ;
    fi
  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" tibdocker.tibco.com"
  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
    source ${TRAVIS_BUILD_DIR}/mashling-cicd/scripts/init.sh ;
    mashling::module::postbuild mashling-lib mashling-lib ;
    fi"
  - cd $GOPATH   
  - rm -rf $GOPATH/src/github.com/TIBCOSoftware/mashling-lib 
  - go get -u github.com/TIBCOSoftware/flogo-lib/...
  - go get -u github.com/TIBCOSoftware/flogo-cli/...
  - go get github.com/TIBCOSoftware/mashling-cli/...
  - go get -u github.com/TIBCOSoftware/mashling-cli/...
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git
  - cd mashling-cicd
  - git checkout -b historical-builds origin/historical-builds
  - pushd sample-recipes
  - chmod ugo+x ./build-recipes.sh
  - ./build-recipes.sh
  - popd
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then      
    pushd mashling-cicd/docker/mashling-sample;
    chmod ugo+x ./build-mashling-sample.sh ;
    ./build-mashling-sample.sh ;
    popd ;
    fi	
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
after_success:  
  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
    source ${TRAVIS_BUILD_DIR}/mashling-cicd/scripts/init.sh;
    mashling::module::postbuild mashling-sample mashling-sample ;
    fi"  
notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - jpark@tibco.com
      - rpolishe@tibco.com
      - lmekala@tibco.com
      - nthota@tibco.com
      - ykalidin@tibco.com
